// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Game struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	ServerID  string
}

type Inventory struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Quantity  int32
	OwnerID   uuid.UUID
	ItemName  string
}

type Item struct {
	Name        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Description sql.NullString
	Category    sql.NullString
}

type Player struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	GameID    uuid.UUID
}

type Server struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
}
